# This is for data analysis learning [freecodecamp](https://www.youtube.com/watch?v=r-uOLxNrNk8&t=14s&ab_channel=freeCodeCamp.org)
Let's goooo!

In [4]:
# import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("Hello World!")

Hello World!


## Numpy learning
Works very similarly to Python lists

In [7]:
a = np.array([1,2,3,4,5])
print(a)
print(a[0])
print(a.dtype)

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(A[1][1])
print(A.shape)
print(A.ndim)
print(A.size)

[1 2 3 4 5]
1
int32
5
(3, 3)
2
9


#### statistics

In [9]:
print(A.sum())

print(A.mean())

print(A.std())

print(A.var())

print(A.sum(axis=0))


45
5.0
2.581988897471611
6.666666666666667
[12 15 18]


# Pandas
### Pandas Dataframes and methods

In [12]:
A[ A < 5 ] = 0 
print(A)

df.columns # returns the column names of the dataframe
df.index # returns the index of the dataframe
df.info() # info returns the data type of each column and if there are any missing values
df.size # returns the number of elements in the dataframe
df.shape # returns the number of rows and columns in the dataframe
df.describe() # returns the count, mean, std, min, 25%, 50%, 75%, max of each column


[[0 0 0]
 [0 5 6]
 [7 8 9]]


In [ ]:
# for rows
df.loc["Canada"] # returns the row with label "Canada" IT'S PREFERED TO USE LOC FOR 
df.loc[["Canada", "Germany"]] # returns the rows with labels "Canada" and "Germany"
df.loc["Canada":"Germany"] # returns the rows with labels "Canada" to "Germany"

df.loc["Canada":"Germany", "Population"] # returns the rows with labels "Canada" to "Germany" and column "Population"
df.loc["Canada":"Germany", ["Population", "GDP"]] # returns the rows with labels "Canada" to "Germany" and columns "Population" and "GDP"

df.iloc[0] # returns the first row
df.iloc[[0, 1]] # returns the first and second rows
# the differnce between loc and iloc is that loc is inclusive of the last element and iloc is not

# for columns
df['Population'] # returns the entire column with label "Population"

### Conditional selection

In [ ]:
df.loc[df['Population'] > 1000000] # returns the rows where the population is greater than 1000000
df.loc[(df['Population'] > 1000000) & (df['GDP'] > 1000000)] # returns the rows where the population is greater than 1000000 and the GDP is greater than 1000000


### Dropping

In [ ]:
df_dropped = df.drop("Canada") # drops the row with label "Canada"
df.drop(["Canada", "Germany"]) # drops the rows with labels "Canada" and "Germany"
df.drop(columns=["Population"]) # drops the column "Population"
df.drop(columns=["Population", "GDP"]) # drops the columns "Population" and "GDP"

### Modifying

In [ ]:
df[df['Population'] < 50000] = 0 # sets the rows where the population is less than 50000 to 0


df['GDP per Capita'] = df['GDP'] / df['Population'] # creates a new column "GDP per Capita" by dividing the "GDP" column by the "Population" column

### Reading external data and Plotting

In [ ]:
df = pd.read_csv("file.csv") # reads a csv file and returns a dataframe
df.to_csv("file.csv") # writes a dataframe to a csv file
df = pd.read_excel("file.xlsx") # reads an excel file and returns a dataframe
df.to_excel("file.xlsx") # writes a dataframe to an excel file

df = pd.read_csv("file.csv", index_col=0) # reads a csv file and sets the first column as the index
df = pd.read_csv("file.csv", header=None) # reads a csv file and sets the first row as the header

df['Date'] = pd.to_datetime(df['Date']) # converts the "Date" column to datetime
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d') # converts the "Date" column to a string in the format "YYYY-MM-DD"



# Plotting

In [ ]:
prices.loc['2017-12-01':'2017-12-31'].plot(figsize=(10, 5))

# Data Cleaning

##### normal process
1.- Missing data \n


In [ ]:
missing_values = df.isnull() # returns a dataframe of the same size as df with True where there are missing values and False where there are not
missing_values = df.notnull() # returns a dataframe of the same size as df with False where there are missing values and True where there are not
df.dropna() # drops the rows with missing values
df.dropna(axis=1) # drops the columns with missing values
df.fillna(0) # fills the missing values with 0
df.fillna(method='ffill') # fills the missing values with the previous value
df.fillna(method='bfill') # fills the missing values with the next value
# fill with mean of 
df['Price'].fillna(df['Price'].mean(), inplace=True) # fills the missing values in the "Price" column with the mean of the column

### Invalidate datas and duplicate data

In [ ]:
# Find unique values in a column
df['Country'].unique() # returns an array of the unique values in the "Country" column
df['Country'].count() # returns the number of non-missing values in the "Country" column 
df['Country'].value_counts() # returns a series of the unique values in the "Country" column and their counts

# remove duplicates
df.drop_duplicates() # drops the duplicate rows
df.drop_duplicates(subset=['Country']) # drops the rows where the "Country" column is duplicated
df.drop_duplicates(subset=['Country'], keep='last') # drops the rows where the "Country" column is duplicated, keeping the last occurrence7
df.drop_duplicates(subset=['Country'], keep='first') # drops the rows where the "Country" column is duplicated, keeping the first occurrence


### String methods

In [ ]:
#string operations
df['Country'].str.lower() # converts the "Country" column to lowercase
df['Country'].str.upper() # converts the "Country" column to uppercase
df['Country'].str.len() # returns the length of the "Country" column
df['Country'].str.contains('land') # returns a boolean array where the "Country" column contains the string "land"
df['Country'].str.replace('land', 'LAND') # replaces the string "land" with "LAND" in the "Country" column
df['Country'].str.split(' ') # splits the "Country" column by whitespace
df['Country'].str.split(' ', expand=True) # splits the "Country" column by whitespace and returns a dataframe
df['Country'].str.cat(sep=', ') # concatenates the "Country" column with ", " as the separator
df['Country'].str.get(0) # returns the first character of the "Country" column
df['Country'].str[0] # returns the first character of the "Country" column
df['Country'].str[0:3] # returns the first three characters of the "Country" column
df['Country'].str.slice(0, 3) # returns the first three characters of the "Country" column
df['Country'].str.startswith('A') # returns a boolean array where the "Country" column starts with the letter "A"
df['Country'].str.endswith('a') # returns a boolean array where the "Country" column ends with the letter "a"
df['Country'].str.find('a') # returns the position of the first occurrence of the letter "a" in the "Country" column
df['Country'].str.findall('a') # returns a list of all occurrences of the letter "a" in the "Country" column
df['Country'].str.extract('([A-Za-z]+)') # extracts the first word from the "Country" column
df['Country'].str.extractall('([A-Za-z]+)') # extracts all words from the "Country" column
df['Country'].str.contains('land') # returns a boolean array where the "Country" column contains the string "land"
df['Country'].str.match('A') # returns a boolean array where the "Country" column starts with the letter "A"
df['Country'].str.len() # returns the length of the "Country" column
df['Country'].str.isnumeric() # returns a boolean array where the "Country" column is numeric
df['Country'].str.isalpha() # returns a boolean array where the "Country" column is alphabetic
df['Country'].str.isalnum() # returns a boolean array where the "Country" column is alphanumeric
df['Country'].str.islower() # returns a boolean array where the "Country" column is lowercase
df['Country'].str.isupper() # returns a boolean array where the "Country" column is uppercase
df['Country'].str.isspace() # returns a boolean array where the "Country" column is whitespace
df['Country'].str.isdecimal() # returns a boolean array where the "Country" column is decimal
df['Country'].str.isnumeric() # returns a boolean array where the "Country" column is numeric
df['Country'].str.isdigit() # returns a boolean array where the "Country" column is digit

df['Country'].str.strip() # removes leading and trailing whitespace from the "Country" column
df['Country'].str.lstrip() # removes leading whitespace from the "Country" column
df['Country'].str.rstrip() # removes trailing whitespace from the "Country" column
df['Country'].str.pad(width=10, side='left', fillchar='-') # pads the "Country" column with "-" on the left to a width of 10
df['Country'].str.center(width=10, fillchar='-') # centers the "Country" column with "-" to a width of 10

